apiVersion: v1
kind: Service
metadata:
  name: blocks-user-service  
spec:
  selector:
    app.kubernetes.io/name: blocks-user-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
