apiVersion: v1
kind: Service
metadata:
  name: blocks-user-db  
  labels:
    app.kubernetes.io/name: blocks-user-db
spec:
  selector:
    app.kubernetes.io/name: blocks-user-db
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: mysql