apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocks-execution-service
  labels:
    app: blocks-execution-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blocks-execution-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blocks-execution-service
    spec:
      initContainers:
      - name: dep-blocks-user-db-readiness
        image: busybox:stable
        command: ['sh', '-c', 
          'echo -e "Checking for the availability of blocks-user-db deployment"; 
          while ! nc -z blocks-user-db 3306; 
          do sleep 1; printf "-"; 
          done; 
          echo -e "  >> blocks-user-db has started";']
      # - name: dep-blocks-mongodb-readiness
      #   image: busybox:stable
      #   command: ['sh', '-c', 
      #     'echo -e "Checking for the availability of blocks-mongodb deployment"; 
      #     while ! nc -z blocks-mongodb 27017; 
      #     do sleep 1; printf "-"; 
      #     done; 
      #     echo -e "  >>blocks-mongodb has started";']
      - name: dep-blocks-scenery-service-readiness
        image: busybox:stable
        command: ['sh', '-c', 
          'echo -e "Checking for the availability of blocks-scenery-service deployment"; 
          while ! nc -z blocks-scenery-service 8082; 
          do sleep 1; printf "-"; 
          done; 
          echo -e "  >>blocks-scenery-service has started";']          
      containers:
      - name: blocks-execution-service
        image: registry.vericode.com.br/sinacor.blocks.execution.service:0.0.19
        ports:
        - containerPort: 8080
