apiVersion: v1
kind: Service
metadata:
  name: blocks-execution-service  
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  selector:
    app.kubernetes.io/name: blocks-execution-service