apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocks-feature-toggle-service
  labels:
    app: blocks-feature-toggle-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blocks-feature-toggle-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blocks-feature-toggle-service
    spec:
      initContainers:
      - name: dep-blocks-user-db-readiness
        image: busybox:stable
        command: ['sh', '-c',
          'echo -e "Checking for the availability of blocks-user-db deployment"; 
          while ! nc -z blocks-user-db 3306; 
          do sleep 1; printf "-"; 
          done; 
          echo -e "  >> blocks-user-db has started";']
      containers:
      - name: blocks-feature-toggle-service
        image: registry.vericode.com.br/sinacor.blocks.feature-toggle.service:0.0.11
        ports:
        - containerPort: 8080
