apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blocks-sbe-node-namespace-admin-binding
subjects:
  - kind: ServiceAccount
    name: blocks-sbe-node-service-account
roleRef:
  kind: Role
  name: blocks-sbe-node-namespace-admin-role
  apiGroup: rbac.authorization.k8s.io