apiVersion: v1
kind: Service
metadata:
  name: blocks-sbe-node
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 9000
  selector:
    app.kubernetes.io/name: blocks-sbe-node