apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocks-scenery-service
  labels:
    app.kubernetes.io/name: blocks-scenery-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blocks-scenery-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blocks-scenery-service
    spec:
      initContainers:
      - name: dep-blocks-mongodb-readiness
        image: busybox:stable
        command: ['sh', '-c', 
          'echo -e "Checking for the availability of blocks-mongodb deployment"; 
          while ! nc -z blocks-mongodb 27017; 
          do sleep 1; printf "-"; 
          done; 
          echo -e "  >>blocks-mongodb has started";']
      containers:
      - name: blocks-scenery-service
        image: registry.vericode.com.br/sinacor.blocks.scenary.service:0.0.23
        ports:
        - containerPort: 8080
          name: server-port