apiVersion: v1
kind: Service
metadata:
  name: blocks-scenery-service  
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  selector:
    app.kubernetes.io/name: blocks-scenery-service