apiVersion: v1
kind: Service
metadata:
  labels:
    app: blocks-mongodb
  name: blocks-mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: blocks-mongodb