apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /
    server: nfs-server.dott-qa.svc.cluster.local
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
